[package]
name = "spaces_client"
version = "0.0.7"
edition = "2021"

[[bin]]
name = "space-cli"
path = "src/bin/space-cli.rs"

[[bin]]
name = "spaced"
path = "src/bin/spaced.rs"

[lib]
path = "src/lib.rs"

[dependencies]
spaces_wallet = { path = "../wallet" }
spaces_protocol = { path = "../protocol", features = ["std"] }
spaces_ptr = { path = "../ptr", features = ["std"] }
spacedb = { workspace = true }
borsh_utils = { path = "../borsh_utils" }

tokio = { workspace = true, features = ["signal"] }
anyhow = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
hex = { workspace = true }
rand = { workspace = true }
jsonrpsee = { workspace = true }
directories = { workspace = true }
env_logger = { workspace = true }
serde_json = { workspace = true }
borsh = { version = "1.5", features = ["derive"] }
base64 = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true }
threadpool = { workspace = true }
tabled = { workspace = true }
colored = { workspace = true }
tower = { workspace = true }
hyper = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
predicates = { workspace = true }
spaces_testutil = { path = "../testutil" }
