// AUTO GENERATED by checkpoint-builder. Do not edit manually.
pub fn checkpoint() -> super::Checkpoint {
    super::Checkpoint {
        height: 967068,
        block_hash: "000000000000000000004e491bdb3beadd39ff6868a7e90299116d795b984c95".to_string(),
        digest: "d8041896e14c3be70401a83d063fb8c4ec90c32e9619ebbcdea2d2cb3f7e5453".to_string(),
    }
}
