// AUTO GENERATED by checkpoint-builder. Do not edit manually.
pub fn checkpoint() -> super::Checkpoint {
    super::Checkpoint {
        height: 942840,
        block_hash: "00000000000000000000b912ea7ee51e24fb4f55cc4ba6be2fcd9f451ec149e5".to_string(),
        digest: "b1a613e9df54ad75a0c267dfe46d77928f421727228a317d356fd886538281ca".to_string(),
    }
}