[package]
name = "spaces_nums"
description = "Numeric identifier extension for the Spaces protocol."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[dependencies]
bitcoin = { version = "0.32.8", features = ["base64", "serde"], default-features = false }
spaces_protocol = { workspace = true }

## optional features
borsh = { version = "1.5", default-features = false, features = ["derive"], optional = true }
borsh_utils = { workspace = true, optional = true }
serde = { version = "1.0", features = ["derive"], default-features = false, optional = true }
bech32 = { workspace = true, optional = true }
hex = { workspace = true, optional = true }
log = "0.4.29"

[features]
default = ["std"]
serde = ["dep:serde", "dep:hex", "spaces_protocol/serde"]
borsh = ["dep:borsh", "dep:borsh_utils", "spaces_protocol/borsh"]
bech32 = ["dep:bech32"]
std = ["serde", "borsh", "bech32"]
