[package]
name = "spaces_testutil"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "db-dump"
path = "src/bin/db_dump.rs"

[dependencies]
bitcoind = { workspace = true }
spaces_client = { path = "../client" }
assert_cmd = { workspace = true }
anyhow = { workspace = true }
hex = { workspace = true }
spacedb = { workspace = true }
spaces_protocol = { path = "../protocol", features = ["std", "serde"] }
borsh = { version = "1.5", features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true }

[build-dependencies]
zip = { workspace = true }
anyhow = { workspace = true }
